#SimpleRNN(1)

In [14]:
import tensorflow as tf
from keras.layers import Input, Dense, SimpleRNN
from keras.models import Model
import numpy as np

In [15]:
# 입력값의 형태를 지정합니다.
inputs = Input(shape=(1,2))
"""
RNN 셀의 속성을 지정합니다.
3: 3차원 벡터의 출력값을 지정합니다.
return_state=True: RNN 셀의 상태값(state)를 출력하도록 지정합니다.
"""
output, state = SimpleRNN(3, return_state=True)(inputs)
model = Model(inputs=inputs, outputs=[output, state])

In [21]:
model.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 1, 2)]            0         
                                                                 
 simple_rnn_1 (SimpleRNN)    [(None, 3),               18        
                              (None, 3)]                         
                                                                 
Total params: 18
Trainable params: 18
Non-trainable params: 0
_________________________________________________________________


In [16]:
# 테스트 입력값
data = np.array([
                 [ [1,2] ]
                 ])
print(data.shape)

(1, 1, 2)


In [17]:
# 출력값, 상태값 프린트
output, state = model.predict(data)
print("output: ",output)
print("state: ",state)

output:  [[ 0.45066965 -0.6799784   0.89028734]]
state:  [[ 0.45066965 -0.6799784   0.89028734]]


In [18]:
# 입력값에 대한 가중치 행렬의 값을 확인합니다.
model.layers[1].weights[0]

<tf.Variable 'simple_rnn_1/simple_rnn_cell_1/kernel:0' shape=(2, 3) dtype=float32, numpy=
array([[-0.93918836,  0.6101078 ,  0.9199364 ],
       [ 0.7123643 , -0.7195908 ,  0.25168657]], dtype=float32)>

In [19]:
# 이전 상태값에 대한 가중치 행렬의 값을 확인합니다.
model.layers[1].weights[1]

<tf.Variable 'simple_rnn_1/simple_rnn_cell_1/recurrent_kernel:0' shape=(3, 3) dtype=float32, numpy=
array([[-0.61634314, -0.46126813,  0.638242  ],
       [ 0.55045176, -0.83195233, -0.06970067],
       [-0.5631376 , -0.30836192, -0.766674  ]], dtype=float32)>

In [20]:
# 편향값 행렬의 값을 확인합니다.
model.layers[1].weights[2]

<tf.Variable 'simple_rnn_1/simple_rnn_cell_1/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>

#SimpleRNN(2)

In [41]:
# 입력값의 형태를 지정합니다.
inputs = Input(shape=(4, 4))
"""
RNN 셀의 속성을 지정합니다.
3: 3차원 벡터의 출력값 지정합니다.
return_state=True: RNN 셀의 상태값(state)를 출력하도록 지정합니다.
return_sequences=True: RNN 셀의 모든 상태값(state)를 출력하도록 지정합니다.
"""
output, state = SimpleRNN(3, return_state=True, return_sequences=True)(inputs)
model = Model(inputs=inputs, outputs=[output, state])

In [42]:
# I      [1,0,0,0]
# work   [0,1,0,0]
# at     [0,0,1,0]
# google [0,0,0,1]
#
# I work at google =  [ [1,0,0,0], [0,1,0,0], [0,0,1,0], [0,0,0,1] ]
# I google at work =  [ [1,0,0,0], [0,0,0,1], [0,0,1,0], [0,1,0,0] ]

# 테스트 입력값
data = np.array([
    [ [1,0,0,0], [0,1,0,0], [0,0,1,0], [0,0,0,1] ],
    [ [1,0,0,0], [0,0,0,1], [0,0,1,0], [0,1,0,0] ]
])
print(data.shape)

(2, 4, 4)


In [43]:
# 출력값, 상태값 프린트
output, state = model.predict(data)

In [44]:
print("I work at google: ",output[0])
print("I google at work: ",output[1])

I work at google:  [[ 0.6794635  -0.511487    0.2309484 ]
 [-0.182837    0.25773084  0.30900097]
 [ 0.29169878 -0.23371565 -0.80012417]
 [ 0.63357455 -0.7209327   0.88321584]]
I google at work:  [[ 0.6794635  -0.511487    0.2309484 ]
 [-0.08973227 -0.8340914   0.59155357]
 [ 0.23980874 -0.86185956 -0.9023305 ]
 [ 0.69189245 -0.04855507  0.75049025]]


In [45]:
print("I work at google: state: ",state[0])
print("I google at work: state: ",state[1])

I work at google: state:  [ 0.63357455 -0.7209327   0.88321584]
I google at work: state:  [ 0.69189245 -0.04855507  0.75049025]
